//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIP.System.Models.Entities {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceSystem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSystem() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIP.System.Models.Entities.ResourceSystem", typeof(ResourceSystem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 具有下级项,请删除下级项后重试 的本地化字符串。
        /// </summary>
        public static string 具有下级项 {
            get {
                return ResourceManager.GetString("具有下级项", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已具有人员,请删除人员后重试 的本地化字符串。
        /// </summary>
        public static string 具有人员 {
            get {
                return ResourceManager.GetString("具有人员", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已具有功能项权限,请取消功能项权限后重试 的本地化字符串。
        /// </summary>
        public static string 具有功能项权限 {
            get {
                return ResourceManager.GetString("具有功能项权限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已具有岗位,请删除岗位后重试 的本地化字符串。
        /// </summary>
        public static string 具有岗位 {
            get {
                return ResourceManager.GetString("具有岗位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已具有组,请删除组后重试 的本地化字符串。
        /// </summary>
        public static string 具有组 {
            get {
                return ResourceManager.GetString("具有组", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已具有菜单权限,请取消菜单权限后重试 的本地化字符串。
        /// </summary>
        public static string 具有菜单权限 {
            get {
                return ResourceManager.GetString("具有菜单权限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已具有角色,请删除角色后重试 的本地化字符串。
        /// </summary>
        public static string 具有角色 {
            get {
                return ResourceManager.GetString("具有角色", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已被赋予权限,请取消权限后重试 的本地化字符串。
        /// </summary>
        public static string 已被赋予权限 {
            get {
                return ResourceManager.GetString("已被赋予权限", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码错误 的本地化字符串。
        /// </summary>
        public static string 用户名或密码错误 {
            get {
                return ResourceManager.GetString("用户名或密码错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败,用户帐号被冻结 的本地化字符串。
        /// </summary>
        public static string 登录用户已冻结 {
            get {
                return ResourceManager.GetString("登录用户已冻结", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置密码成功,密码为【{0}】 的本地化字符串。
        /// </summary>
        public static string 重置密码成功 {
            get {
                return ResourceManager.GetString("重置密码成功", resourceCulture);
            }
        }
    }
}
